Improve coverage reports and documentation update with GitLab (#26)
* Skip everything related to coveralls
* Upload coverage reports to the project wiki
* Upload documentation to the project wiki

To be evaluated/discussed:

All of this is done for a single branch and a single build, is it
enough? How to allow more knowing that wiki branches exist but are not
accesible through the web interface?

Coverage reports are kept for each commits and a page is created to
access all revisions' report. The rational is that it is interesting to
know whether or not your coverage evolved and coverage reports are
light.

Should we put coverage.info on the repository?

Documentation is strictly updated so only one revision is available at
anytime. The rational is that documentation is heavy and its history is
less interesting. For release documentation, the process can be done
manually by the developpers.

diff --git a/after_success b/after_success
--- a/after_success
+++ b/after_success
@@ -9,6 +9,19 @@ set -v
 #  --  Helper functions  --  #
 ##############################
 
+clone_wiki()
+{
+  # wiki_dir is set here if this build is meant to update the wiki
+  export CI_UPDATE_WIKI=${CI_UPDATE_WIKI:-false}
+  export CI_UPDATE_WIKI_BRANCH=${CI_UPDATE_WIKI_BRANCH:-master}
+  if [[ ${CI_WIKI} != "" && ${CI_UPDATE_WIKI} = true && ${CI_UPDATE_WIKI_BRANCH} = ${CI_BRANCH} ]]; then
+    export wiki_dir="/tmp/_ci_wiki"
+    git clone --depth 1 "$CI_WIKI" "$wiki_dir"
+  else
+    export wiki_dir=""
+  fi
+}
+
 upload_to_ppa()
 {
   if `test x${DIST} = x`; then
@@ -30,24 +43,57 @@ upload_to_ppa()
   fi
 }
 
+make_coverage()
+{
+  cd $build_dir
+  # If tests failed, coveralls data may not have been written
+  lcov --directory $build_dir --base-directory $root_dir --capture --output-file coverage.info || true
+  # Note: ignore rules are given by a string such as "*test* *foo*"
+  # lcov expects: '*test*' '*foo*'
+  # We use -f to prevent expansion of *
+  set -f
+  lcov --remove coverage.info '/usr*' "$install_dir*" ${LCOV_IGNORE_RULES} -o coverage.info || true
+  set +f
+}
+
+make_coverage_report()
+{
+  cd $root_dir
+  HEAD=`git rev-parse HEAD`
+  genhtml --prefix "$root_dir" --ignore-errors source "$build_dir/coverage.info" --legend --title "Coverage report for $CI_REPO_SLUG (rev: $HEAD)" --output-directory="$wiki_dir/coverage_$HEAD"
+  cd $wiki_dir
+  if [[ ! -f coverage.markdown ]]; then
+    touch coverage.markdown
+  fi
+  # TODO Add more information on this page?
+  touch coverage.markdown.tmp
+  echo -e "Coverage information for commit [$HEAD](coverage_$HEAD/index.html)\n\n$(cat coverage.markdown)" > coverage.markdown
+  git add coverage_$HEAD coverage.markdown
+}
+
+upload_coverage_to_coveralls()
+{
+  cd $root_dir
+  coveralls-lcov "$build_dir/coverage.info" || true
+  cd -
+}
+
 generate_coverage_data()
 {
-  # Upload coveralls data.
-  if [ x${CC} = xgcc ]; then
-    cd $build_dir
-    # If tests failed, coveralls data may not have been written
-    lcov --directory $build_dir --base-directory $root_dir --capture --output-file coverage.info || true
-    # Note: ignore rules are given by a string such as "*test* *foo*"
-    # lcov expects: '*test*' '*foo*'
-    # We use -f to prevent expansion of *
-    set -f
-    lcov --remove coverage.info '/usr*' "$install_dir*" ${LCOV_IGNORE_RULES} -o coverage.info || true
-    set +f
-    cd $root_dir
-    coveralls-lcov "$build_dir/coverage.info" || true
-    cd -
+  if [[ ${CI_SUPPORT_COVERALLS} = true ]]; then
+    # Upload coveralls data.
+    if [ x${CC} = xgcc ]; then
+      make_coverage
+      upload_coverage
+    else
+      echo "skipping coveralls upload in non-gcc builds"
+    fi
   else
-    echo "skipping coveralls upload in non-gcc builds"
+    # Always generate coverage data to get the information on GitLab build page
+    make_coverage
+    if [[ -d $wiki_dir ]]; then
+      make_coverage_report
+    fi
   fi
 }
 
@@ -68,6 +114,22 @@ set_push_uri()
     git remote set-url origin "${GH_PUSH_URI}"
   fi
   return 0
+}
+
+update_wiki_documentation()
+{
+  # Replace svg iframe inclusion by img
+  cd $wiki_dir
+  git rm -rf $wiki_dir/doxygen-html
+  cp -r $build_dir/doc/doxygen-html $wiki_dir
+  cd $wiki_dir/doxygen-html
+  sed -i -e's@<iframe .* src="\(.*\).svg" width="\(.*\)" height="\(.*\)"><p><b>\(.*\)</b></p></iframe>@<img src="\1.svg" width="\2" height="\3" alt="\4" />@' *.html
+  cd $wiki_dir
+  git add doxygen-html
+  if [[ ! -f doxygen.markdown ]]; then
+    echo "Doxygen documentation can be accessed [here](doxygen-html/index.html)" > doxygen.markdown
+    git add doxygen.markdown
+  fi
 }
 
 update_documentation()
@@ -101,6 +163,16 @@ push_note()
   git push origin refs/notes/jrl-ci --force
 }
 
+update_wiki()
+{
+  if [[ -d $wiki_dir ]];
+  then
+    cd $wiki_dir
+    git commit -a -m "[CI] Update wiki documentation and coverage reports"
+    git push
+  fi
+}
+
 #########################
 #  --  Main script  --  #
 #########################
@@ -113,6 +185,8 @@ elif [[ ${CI_OS_NAME} = linux ]]; then
       exit 0
     fi
 
+    clone_wiki
+
     if [[ ";${DO_COVERAGE_ON_BRANCH};" == *";${CI_BRANCH};"* ]]; then
       generate_coverage_data
     fi
@@ -124,9 +198,13 @@ elif [[ ${CI_OS_NAME} = linux ]]; then
         update_documentation
         push_note
       fi
+    elif [[ -d $wiki_dir ]]; then
+      update_wiki_documentation
     else
       echo "skipping doc/build result upload on forks and for pull requests"
     fi
+
+    update_wiki
 fi
 
 # End debug mode
